name: Supabase Cron Job

on:
  schedule:
    - cron: '0 5 * * *'
    - cron: '30 1 * * 1-5'
    - cron: '45 9 * * 1-5'
    - cron: '30 2 * * 6'
    - cron: '45 10 * * 6'
    - cron: '30 3 * * 0'
    - cron: '45 11 * * 0'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      # 👇 เพิ่มขั้นตอนติดตั้ง Driver ของ Microsoft ให้ GitHub ยอมรับ pyodbc
      - name: Install MS SQL ODBC Driver
        run: |
          curl https://packages.microsoft.com/keys/microsoft.asc | sudo tee /etc/apt/trusted.gpg.d/microsoft.asc
          curl https://packages.microsoft.com/config/ubuntu/22.04/prod.list | sudo tee /etc/apt/sources.list.d/mssql-release.list
          sudo apt-get update
          sudo ACCEPT_EULA=Y apt-get install -y msodbcsql18 unixodbc-dev

      - name: Install libraries
        run: |
          pip install -r requirements.txt

      - name: Run script
        env:
          LINE_CHANNEL_ACCESS_TOKEN: ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          AZURE_SERVER: ${{ secrets.AZURE_SERVER }}
          AZURE_DB: ${{ secrets.AZURE_DB }}
          AZURE_USER: ${{ secrets.AZURE_USER }}
          AZURE_PASS: ${{ secrets.AZURE_PASS }}
        run: python main.py
